CREATE TABLE NEAR_EARTH_OBJECT(
  ID INT NOT NULL PRIMARY KEY,
  NAME VARCHAR(255),
  NASA_JPL_URL VARCHAR(255),
  ABSOLUTE_MAGNITUDE_H DOUBLE,
  ESTIMATED_DIAMETER_MIN DOUBLE,
  ESTIMATED_DIAMETER_MAX DOUBLE,
  IS_POTENTIALLY_HAZARDOUS BOOLEAN NOT NULL,
  RELATIVE_VELOCITY DOUBLE,
  MISS_DISTANCE DOUBLE,
  ORBITING_BODY VARCHAR(255)
);